### PR TITLE
perf: Make icon components functional

### PR DESCRIPTION
**Pull request by danielroe**
[Re-submitting #33]

Because functional components don't have the full Vue lifecycle, they seem ideally suited for a project like this one. Let me know if you would like me to make any additional changes to the PR.

### CODE REVIEW

**Comment by robcresswell** [comment]
Great, they ran this time, thanks for reopening!

**Comment by danielroe** [comment]
@robcresswell I'll look at the tests! :smile:

**Comment by robcresswell** [comment]
Great, thanks; no rush, I'll keep an eye out for when you get chance to do it. And if you get too bogged down in it, yell and I'll take a look.

**Comment by danielroe** [comment]
Thanks @robcresswell - all done. I've removed the tests on the internal state of the component given that functional components don't have an instance. Let me know if you feel that it needs more tests.

**Comment by robcresswell** [comment]
I think the snapshot is adequate for covering that info, so its all good. Thanks Daniel! I'll merge and tag a release later tonight / tomorrow, depending on time.

**Comment by danielroe** [comment]
@robcresswell Do you need me to make any further changes?

**Comment by robcresswell** [comment]
@danielroe Thanks for reminding me about this, sorry. Have rolled these into #46. Wanted to rewrite the commit messages to trigger semantic release correctly, without pestering your for further work.

**Comment by robcresswell** [comment]
I kept your commits etc, so the authorship is still under your name. Thanks for your contribution!

**Comment by danielroe** [comment]
Thanks @robcresswell - and that's kind of you. :smiley:

**Comment by robcresswell** [comment]
@danielroe I don't suppose you'd be able to help out with https://github.com/robcresswell/vue-material-design-icons/issues/49 ? No worries if not :innocent:

**Pull request closed without merging**
