### PR TITLE
Remove title when purely decorative.

### PR DESCRIPTION
**Pull request by scoxatpush**
Addresses issue #115 with the trivial suggestion (remove title element when decorative flag is set)

### CODE REVIEW

**Comment by robcresswell** [comment]
This seems good to me. Would you mind updating the commit message to follow semantic release guidelines?

```
feat: remove title when purely decorative
```

**Comment by scoxatpush** [comment]
My apologies; I was in a rush.

**Comment by scoxatpush** [comment]
The more I think about this, the less I like it. It's probably going to break somebody's use case in a counter-intuitive way, for example if they've explicitly set the title prop.

**Comment by robcresswell** [comment]
Do we care if someone has explicitly set a title when the icon is decorative only? Not sure that's a valid use case 

I'm tempted to merge this, and release it alongside Vue 3 support as a possibly breaking change

**Comment by scoxatpush** [comment]
Any updates on those plans @robcresswell ?

**Comment by robcresswell** [comment]
Hey @scoxatpush I pushed your commit as part of #264. I wanted to update the commit message so semver tags it as a bugfix, but it felt rude asking after so many months. Thanks for your fix!

**Pull request closed without merging**
